server:
  port: 8881

spring:
  application:
    name: proposal-service
  datasource:
    url: jdbc:hsqldb:file:data/mydb
    username: sa
    password:
    driverClassName: org.hsqldb.jdbcDriver
  jpa:
    hibernate:
      ddl-auto: none